"""first

Revision ID: 45d6c2784b4a
Revises: bc9704f27fc8
Create Date: 2025-02-21 11:37:51.778930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45d6c2784b4a'
down_revision: Union[str, None] = 'bc9704f27fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=postgresql.ENUM('pending', 'completed', name='taskstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('pending', 'completed', name='taskstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
